name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm i
      - run: npm run build_server
      - run: npm run build

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git rm -f client.exe || true
          git add client.exe
          git commit -m "build"
          git push origin main

      - run: |
          git checkout -b server
          git rm -r .
          git checkout main -- server.js
          git add server.js
          git commit -m "build"
          git push origin server --force
